#!/usr/bin/env bash

# 🐻‍❄️💐 ume: Easy, self-hostable, and flexible image host made in Rust
# Copyright 2021-2024 Noel Towa <cutie@floofy.dev>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

while [ -L "$BASH_SRC" ]; do
    target=$(readlink "$BASH_SRC")
    if [[ $target == /* ]]; then
        BASH_SRC=$target
    else
        dir=$(dirname "$BASH_SRC")
        BASH_SRC=$dir/$target
    fi
done

DIR=$(cd -P "$(dirname "$BASH_SRC")/distribution/helm" >/dev/null 2>&1 && pwd)

if ! command -v bun >/dev/null; then
    echo "[ERROR] ===> Missing \`bun\` in host machine, install it please!"
    exit 1
fi

! [ -d "$DIR/.cache" ] && mkdir -p "$DIR/.cache"

if ! [ -d "$DIR/.cache/bitnami-helm-gen" ]; then
    echo "===> Missing $DIR/.cache/bitnami-helm-gen directory, installing..."

    git clone https://github.com/bitnami-labs/readme-generator-for-helm "$DIR/.cache/bitnami-helm-gen"
    bun install "$DIR/.cache/bitnami-helm-gen"
fi

echo ".... Generating..."
(cd "$DIR/.cache/bitnami-helm-gen" && bun --bun bin/index.js --values "$DIR/values.yml" --readme "$DIR/README.md")

if [ "$?" != "0" ]; then
    echo ".... Failed to generate, view logs above"
    exit 1
fi
