# 🐻‍❄️💐 ume: Easy, self-hostable, and flexible image host made in Rust
# Copyright 2021-2025 Noel Towa <cutie@floofy.dev>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
## @section :sparkles: Global Parameters
## @descriptionStart
## Parameters that affect all objects in this Helm chart.
## @descriptionEnd
##
## @param global.replicas                 Amount of replicas to use. At the moment, **ume** is not used in HA.
## @param global.resources                [object] [Resources][k8s-resources] to apply to all containers.
## @param global.fullNameOverride         String to fully override the Helm installation name for all objects
## @param global.nameOverride             String to override the Helm installation name for all objects, will be in conjunction with a prefix of `<install-name>-`
## @param global.clusterDomain            Domain host that maps to the cluster
## @param global.nodeSelector             Selector labels to apply to contraint the pods to specific nodes. Read more in the [Kubernetes documentation][k8s-node-selector].
## @param global.tolerations              List of all taints/tolerations to apply in conjunction with [`global.affinity`][global-affinity]. Read more in the [Kubernetes documentation][k8s-taint-and-toleration]
## @param global.affinity                 Map of all the affinity to apply to the spawned Pods. Read more in the [Kubernetes documentation][k8s-node-affinity].
## @param global.annotations              Map of annotations to append to on all objects that this Helm chart creates.
## @param global.extraEnvVars             List of extra environment variables to append to all init/sidecar containers and normal containers.
## @param global.initContainers           A list of init containers to spawn alongside the main server.
## @param global.podSecurityContext       Security context for all spawned Pods. Read more in the [Kubernetes documentation][k8s-security-context]
## @param global.containerSecurityContext Security context for all init, sidecar, and normal containers. Read more in the [Kubernetes documentation][k8s-security-context]
## @param global.dnsPolicy                DNS policy for the pod.
## @param global.dnsConfig                Applies a [DNS configuration][k8s-pod-dns-config] for the spawned Pod.
## @param global.domain                   Domain to set so Ume can redirect users who use the service to that URL rather than the local address.
global:
  replicas: 1
  fullNameOverride: ""
  nameOverride: ""
  clusterDomain: cluster.local
  domain: ""
  nodeSelector: {}
  tolerations: []
  affinity: {}
  annotations: {}
  extraEnvVars: []
  initContainers: []
  podSecurityContext: {}
  containerSecurityContext: {}
  resources:
    {}
    ## Example:
    ##  limits:
    ##    memory: 2Gi
    ##    cpu: 1500m
    ##  requests:
    ##    memory: 512Mi
    ##    cpu: 150m

  dnsPolicy: ""
  dnsConfig: {}

## @section :whale: Image Parameters
## @param image.pullPolicy  Image [pull policy][k8s-image-pull-policy] when pulling the image.
## @param image.registry    A qualified URI domain that points to a OCI-compatible registry. For Docker Hub, use an empty string.
## @param image.image       Name of the image itself.
## @param image.tag         Tag of the image. Keep this as an empty string for the chart's default `appVersion`.
## @param image.digest      Uses a digest for the tag of this image in the syntax of `<algorithm>:<hex>`. `image.tag` and `image.digest` are mutually exclusive.
## @param image.pullSecrets Specifies pull secrets for the OCI registry if it is private. Read more in the [Kubernetes documentation][k8s-pull-private-images]
image:
  pullPolicy: IfNotPresent
  registry: "" # keep empty to use docker hub
  image: auguwu/ume
  tag: "" # keep empty for the app version
  digest: ""
  pullSecrets: []
